/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/book-new.glb --transform 
Files: public/models/book-new.glb [64.33KB] > /Users/stephenmatheis/GitHub/quest/book-new-transformed.glb [4.64KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/book-new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_3.geometry} material={materials.Material_3} position={[0.281, 0.008, 0.062]} rotation={[-0.125, 0, 0]} />
      <mesh geometry={nodes.Mesh_7.geometry} material={materials.Material_7} position={[0.219, -0.597, 0.012]} rotation={[-0.125, 0, 0]} />
      <mesh geometry={nodes.Mesh_18.geometry} material={materials.Material_18} position={[-0.698, 0.035, 0.277]} rotation={[-0.125, 0.1, 0]} />
    </group>
  )
}

useGLTF.preload('/book-new-transformed.glb')
