/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SwordWallMount.glb --transform 
Files: public/models/SwordWallMount.glb [136KB] > /Users/stephenmatheis/GitHub/quest/SwordWallMount-transformed.glb [11.11KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SwordWallMount-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sword_WallMount.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/SwordWallMount-transformed.glb')
