// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hand_painted_forest.glb --transform 
Files: public/models/hand_painted_forest.glb [14.8MB] > /Users/stephenmatheis/GitHub/quest/hand_painted_forest-transformed.glb [919.17KB] (94%)
Author: Pasha (https://sketchfab.com/Pasha.)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/hand-painted-forest-8f52416156d24fefb577d6244d7aca7e
Title: Hand painted forest
*/

import { useGLTF } from '@react-three/drei';

export function Forest(props) {
    const { nodes, materials } = useGLTF('/models/hand_painted_forest-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.FrontSide_0.geometry}
                material={materials.TextureMaterial}
                position={[0, 22.571, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_1.geometry}
                material={materials.TextureMaterial_0}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_2.geometry}
                material={materials.TextureMaterial_1}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_3.geometry}
                material={materials.TextureMaterial_2}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_4.geometry}
                material={materials.TextureMaterial_3}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_5.geometry}
                material={materials.TextureMaterial_4}
                position={[0.124, 23.688, -0.032]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_6.geometry}
                material={materials.TextureMaterial_5}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_7.geometry}
                material={materials.TextureMaterial_6}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_8.geometry}
                material={materials.TextureMaterial_7}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_9.geometry}
                material={materials.TextureMaterial_8}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_10.geometry}
                material={materials.TextureMaterial_9}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_11.geometry}
                material={materials.TextureMaterial_10}
                position={[-12.162, 25.221, -3.746]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_1.geometry}
                material={materials.TextureMaterial_1_12}
                position={[-12.162, 25.221, -3.746]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_2.geometry}
                material={materials.TextureMaterial_2_13}
                position={[-12.162, 25.221, -3.746]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_3.geometry}
                material={materials.TextureMaterial_3_14}
                position={[-12.162, 25.221, -3.746]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_12.geometry}
                material={materials.TextureMaterial_11}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_13.geometry}
                material={materials.TextureMaterial_12}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_14.geometry}
                material={materials.TextureMaterial_13}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_15.geometry}
                material={materials.TextureMaterial_14}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_16.geometry}
                material={materials.TextureMaterial_15}
                position={[-8.368, 25.414, -5.87]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_17.geometry}
                material={materials.TextureMaterial_16}
                position={[-8.972, 26.306, -6.162]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_18.geometry}
                material={materials.TextureMaterial_17}
                position={[0.628, 29.695, -21.644]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_19.geometry}
                material={materials.TextureMaterial_18}
                position={[5.864, 36.724, -1.959]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_20.geometry}
                material={materials.TextureMaterial_19}
                position={[8.82, 37.773, -1.861]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_21.geometry}
                material={materials.TextureMaterial_20}
                position={[6.259, 24.829, 10.084]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
            <mesh
                geometry={nodes.FrontSide_0_22.geometry}
                material={materials.TextureMaterial_21}
                position={[0, 23.688, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.394}
            />
        </group>
    );
}

useGLTF.preload('/models/hand_painted_forest-transformed.glb');
