// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stylized_mangrove_greenhouse.glb --transform 
Files: public/models/stylized_mangrove_greenhouse.glb [15.32MB] > /Users/stephenmatheis/GitHub/quest/stylized_mangrove_greenhouse-transformed.glb [642.7KB] (96%)
Author: borsh_and (https://sketchfab.com/borsh_and)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-mangrove-greenhouse-4ad533f838f44fa583683ab7939c6aa1
Title: Stylized Mangrove Greenhouse
*/

import { useGLTF } from '@react-three/drei';

export function Greenhouse(props) {
    const { nodes, materials } = useGLTF('/models/stylized_mangrove_greenhouse-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Cube001_TT_checker_1_0.geometry}
                material={materials.TT_checker_1}
                position={[0, 0.623, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.943}
            />
            <mesh
                geometry={nodes.Cube001_Line_art_0.geometry}
                material={materials.Line_art}
                position={[0, 0.623, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.943}
            />
            <mesh
                geometry={nodes.Cube042_Glass_0.geometry}
                material={materials.Glass}
                position={[0, 0.725, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[4.663, 8.449, 2.501]}
            />
            <mesh
                geometry={nodes.Cube006_TT_checker_3_0.geometry}
                material={materials.TT_checker_3}
                position={[-0.029, 1.342, 0.021]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.819}
            />
            <mesh
                geometry={nodes.Cube006_Line_art__Red_0.geometry}
                material={materials.Line_art__Red}
                position={[-0.029, 1.342, 0.021]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.819}
            />
            <mesh
                geometry={nodes.Circle010_TT_checker_2_0.geometry}
                material={materials.TT_checker_2}
                position={[1.195, 0.977, 7.65]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.009}
            />
            <mesh
                geometry={nodes.BezierCurve_TT_checker_4_0.geometry}
                material={materials.TT_checker_4}
                position={[-1.723, 1.008, -3.907]}
                rotation={[3.114, 0.753, 1.434]}
                scale={0.943}
            />
            <mesh
                geometry={nodes.Circle031_Line_art_Green__0.geometry}
                material={materials.Line_art_Green}
                position={[1.671, 0.482, -2.606]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.528}
            />
            <mesh
                geometry={nodes.Circle034_Material003_0.geometry}
                material={materials['Material.003']}
                position={[0.142, 1.97, 3.654]}
                rotation={[-2.084, -0.271, 0.423]}
                scale={[0.114, 0.117, 0.163]}
            />
            <mesh
                geometry={nodes.Circle055_Material004_0.geometry}
                material={materials['Material.004']}
                position={[0.949, -0.041, 2.804]}
                rotation={[-1.663, -0.513, -1.699]}
                scale={[0.105, 0.105, 0.146]}
            />
            <mesh
                geometry={nodes.Plane021_Leaves_2_0.geometry}
                material={materials.Leaves_2}
                position={[2.95, 6.887, -4.003]}
                rotation={[-2.637, -0.643, 1.936]}
                scale={0.786}
            />
            <mesh
                geometry={nodes.Plane021_Leaves_1_0.geometry}
                material={materials.Leaves_1}
                position={[2.95, 6.887, -4.003]}
                rotation={[-2.637, -0.643, 1.936]}
                scale={0.786}
            />
            <mesh
                geometry={nodes.Plane013_Leaves_3_0.geometry}
                material={materials.Leaves_3}
                position={[6.723, 0.765, -2.349]}
                rotation={[-1.95, -0.37, -1.246]}
                scale={0.492}
            />
            <mesh
                geometry={nodes.Plane018_Leaves_4_0.geometry}
                material={materials.Leaves_4}
                position={[-1.629, 2.739, -4.044]}
                rotation={[-0.993, -0.161, -0.94]}
                scale={[0.553, 0.552, 0.538]}
            />
            <mesh
                geometry={nodes.Plane015_Grass_0.geometry}
                material={materials.Grass}
                position={[5.832, 0.16, 5.287]}
                rotation={[-1.887, 0.009, -1.015]}
                scale={0.566}
            />
            <mesh
                geometry={nodes.Plane011_Leaves__drop_0.geometry}
                material={materials.Leaves__drop}
                position={[5.752, 4.278, -5.1]}
                rotation={[Math.PI, -1.372, Math.PI]}
                scale={0.943}
            />
            <mesh
                geometry={nodes.Plane124_Glow_0.geometry}
                material={materials.Glow}
                position={[3.654, 2.316, 3.414]}
                scale={0.358}
            />
        </group>
    );
}

useGLTF.preload('/models/stylized_mangrove_greenhouse-transformed.glb');
