// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/game_pirate_adventure_map.glb --transform 
Files: public/models/game_pirate_adventure_map.glb [7.85MB] > /Users/stephenmatheis/GitHub/quest/game_pirate_adventure_map-transformed.glb [742.16KB] (91%)
Author: noyou (https://sketchfab.com/zsm123)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-pirate-adventure-map-696dfa212fda4240817615bdccb373d0
Title: Game pirate adventure map
*/

import React from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function PirateAdventure(props) {
    const group = React.useRef();
    const { nodes, materials, animations } = useGLTF('/models/game_pirate_adventure_map-transformed.glb');
    const { actions } = useAnimations(animations, group);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="RootNode">
                    <group name="Camera001" position={[17.694, 523.344, 928.164]} rotation={[0.178, -1.526, -0.262]} />
                </group>
                <mesh
                    name="hw_zhidao210_daolu_01_hw_dixing_0"
                    geometry={nodes.hw_zhidao210_daolu_01_hw_dixing_0.geometry}
                    material={materials.hw_dixing}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="hw_zhidao210_peijing_04_hw_peijing_02_0"
                    geometry={nodes.hw_zhidao210_peijing_04_hw_peijing_02_0.geometry}
                    material={materials.hw_peijing_02}
                    position={[0, 0, 20999.999]}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="hw_zhidao210_peijing_01_hw_peijing_01_0"
                    geometry={nodes.hw_zhidao210_peijing_01_hw_peijing_01_0.geometry}
                    material={materials.hw_peijing_01}
                    position={[0, 0, -0.001]}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="hw_zhidao210_dimian_01_hw_dixing_02_0"
                    geometry={nodes.hw_zhidao210_dimian_01_hw_dixing_02_0.geometry}
                    material={materials.hw_dixing_02}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                    name="hw_wandaoyou_dimian_01_hw_dixing_02_0"
                    geometry={nodes.hw_wandaoyou_dimian_01_hw_dixing_02_0.geometry}
                    material={materials.hw_dixing_02_0}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/models/game_pirate_adventure_map-transformed.glb');
