// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sea_house.glb --transform 
Files: public/models/sea_house.glb [38.52MB] > /Users/stephenmatheis/GitHub/quest/sea_house-transformed.glb [1.03MB] (97%)
Author: Alena Shek (https://sketchfab.com/ShekAlena)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sea-house-bc4782005e9646fb9e6e18df61bfd28d
Title: Sea House
*/

import { useGLTF } from '@react-three/drei';

export function SeaHouse(props) {
    const { nodes, materials } = useGLTF('/models/sea_house-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Object_2.geometry}
                material={materials['11112_sheet_Material__25']}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                geometry={nodes.Object_4.geometry}
                material={materials['11112_sheet_Material__37']}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh geometry={nodes.Object_6.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
    );
}

useGLTF.preload('/models/sea_house-transformed.glb');
