// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stylised_sky_player_home_dioroma.glb --transform 
Files: public/models/stylised_sky_player_home_dioroma.glb [10.76MB] > /Users/stephenmatheis/GitHub/quest/stylised_sky_player_home_dioroma-transformed.glb [629.52KB] (94%)
Author: Sander Vander Meiren (https://sketchfab.com/Sander.Vander.Meiren)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylised-sky-player-home-dioroma-6597e6c9a5184f07a638ac33c08c2ad5
Title: stylised sky player home dioroma
*/

import { useGLTF } from '@react-three/drei';

export function SkyHome(props) {
    const { nodes, materials } = useGLTF('/models/stylised_sky_player_home_dioroma-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.base_tower_wall_0.geometry}
                material={materials.wall}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                geometry={nodes.tower_base_planks_0.geometry}
                material={materials.planks}
                position={[-44.516, 10.647, 10.285]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                geometry={nodes.tree_trunk_bark_0.geometry}
                material={materials.bark}
                position={[47.887, 83.803, 0]}
            />
            <mesh geometry={nodes.roof_roof_0.geometry} material={materials.roof} position={[-19.572, 3.067, 56.714]} />
            <mesh
                geometry={nodes.roof_wooden_skel_no_op_0.geometry}
                material={materials.wooden_skel_no_op}
                position={[-19.572, 3.067, 56.714]}
            />
            <mesh
                geometry={nodes.grass_floor_grass_0.geometry}
                material={materials.grass}
                rotation={[-Math.PI / 2, 0, 1.328]}
            />
            <mesh
                geometry={nodes.leaves_op_branches_0.geometry}
                material={materials.op_branches}
                position={[73.246, 85.207, -36.64]}
                rotation={[-1.861, 0.588, 1.284]}
                scale={0.611}
            />
            <mesh
                geometry={nodes['rocks_Material_#413_0'].geometry}
                material={materials.Material_413}
                position={[-39.558, -18.451, 115.88]}
                rotation={[0.107, 1.046, -0.139]}
                scale={[1.221, 1.208, 1]}
            />
            <mesh
                geometry={nodes['ferns_Material_#650_0'].geometry}
                material={materials.Material_650}
                position={[37.505, 54.789, 11.634]}
                rotation={[-0.002, 0.334, -0.09]}
                scale={0.799}
            />
            <mesh
                geometry={nodes['door_door_+_barrels_0'].geometry}
                material={materials.door__barrels}
                position={[-11.427, 60.918, -3.194]}
                rotation={[0, 0.773, 0]}
                scale={[0.84, 1, 1]}
            />
        </group>
    );
}

useGLTF.preload('/models/stylised_sky_player_home_dioroma-transformed.glb');
