// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stylized_3d_floating_island_and_mine_house.glb --transform 
Files: public/models/stylized_3d_floating_island_and_mine_house.glb [171.39MB] > /Users/stephenmatheis/GitHub/quest/stylized_3d_floating_island_and_mine_house-transformed.glb [17.31MB] (90%)
Author: Skylar Muffin (https://sketchfab.com/boopdesignstudio)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/stylized-3d-floating-island-and-mine-house-3cb24182a8504d439ee4e3c500565ac5
Title: Stylized 3D Floating Island And Mine House
*/

import { useGLTF } from '@react-three/drei';

export function SkyMine(props) {
    const { nodes, materials } = useGLTF('/models/stylized_3d_floating_island_and_mine_house-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Final_Bridge1_SF_Bridge_Mat001_0.geometry}
                material={materials['SF_Bridge_Mat.001']}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Roof_Final_0.geometry}
                material={materials.SF_Roof_Final}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Rocks_Mat_0.geometry}
                material={materials.SF_Rocks_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Windows_Mat_0.geometry}
                material={materials.SF_Windows_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Bush_Mat_0.geometry}
                material={materials.SF_Bush_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_TreeWood_Mat_0.geometry}
                material={materials.SF_TreeWood_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_TreeLeaf_Mat_0.geometry}
                material={materials.SF_TreeLeaf_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_HouseSupport_Mat_0.geometry}
                material={materials.SF_HouseSupport_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_HouseJoins_Mat_0.geometry}
                material={materials.SF_HouseJoins_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Chimney_Mat_0.geometry}
                material={materials.SF_Chimney_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_CutRock_Mat_0.geometry}
                material={materials.SF_CutRock_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Stalagmites_Mat_0.geometry}
                material={materials.SF_Stalagmites_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_WoodTex_Mat_0.geometry}
                material={materials.SF_WoodTex_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_PlasterTex_Mat_0.geometry}
                material={materials.SF_PlasterTex_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_StoneBrick_Mat_0.geometry}
                material={materials.SF_StoneBrick_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Island_Mat_0.geometry}
                material={materials.SF_Island_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_LampGlass_Mat_0.geometry}
                material={materials.SF_LampGlass_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Lamp_Mat_0.geometry}
                material={materials.SF_Lamp_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Candle_Mat_0.geometry}
                material={materials.SF_Candle_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Grass_Mat_0.geometry}
                material={materials.SF_Grass_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Rail_Mat_0.geometry}
                material={materials.SF_Rail_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_GrassCards_Mat_0.geometry}
                material={materials.SF_GrassCards_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Sack_Mat_0.geometry}
                material={materials.SF_Sack_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_MineCart_Mat_0.geometry}
                material={materials.SF_MineCart_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Bridge_Mat_0.geometry}
                material={materials.SF_Bridge_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Door_Mat_0.geometry}
                material={materials.SF_Door_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Water_Mat_0.geometry}
                material={materials.SF_Water_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_Final_Rocks2_Mat_0.geometry}
                material={materials.Final_Rocks2_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_Black_0.geometry}
                material={materials.Black}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_ButterFly_Mat_0.geometry}
                material={materials.SF_ButterFly_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
            <mesh
                geometry={nodes.Final_Bridge1_SF_Lillypad_Mat_0.geometry}
                material={materials.SF_Lillypad_Mat}
                position={[-0.423, -0.018, 0.118]}
                rotation={[0, -0.185, 0]}
                scale={0.01}
            />
        </group>
    );
}

useGLTF.preload('/models/stylized_3d_floating_island_and_mine_house-transformed.glb');
