// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/the_last_stronghold_animated.glb --transform 
Files: public/models/the_last_stronghold_animated.glb [54.42MB] > /Users/stephenmatheis/GitHub/quest/the_last_stronghold_animated-transformed.glb [2.06MB] (96%)
Author: Conrad Justin (https://sketchfab.com/ConradJustin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/the-last-stronghold-animated-6b4ac951cefb43a791b2bd084b53a201
Title: The Last Stronghold (animated)
*/

import React from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

export function Stronghold(props) {
    const group = React.useRef();
    const { scene, animations } = useGLTF('/models/the_last_stronghold_animated-transformed.glb');
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    const { actions } = useAnimations(animations, group);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <primitive object={nodes._rootJoint} />
                <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.sky_sketchfab}
                    skeleton={nodes.Object_18.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.final_gate_low}
                    skeleton={nodes.Object_20.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.final_alfa}
                    skeleton={nodes.Object_22.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_24"
                    geometry={nodes.Object_24.geometry}
                    material={materials.final_gate_top}
                    skeleton={nodes.Object_24.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_26"
                    geometry={nodes.Object_26.geometry}
                    material={materials.final_C}
                    skeleton={nodes.Object_26.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_28"
                    geometry={nodes.Object_28.geometry}
                    material={materials.final_B}
                    skeleton={nodes.Object_28.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_30"
                    geometry={nodes.Object_30.geometry}
                    material={materials.final_SOMT}
                    skeleton={nodes.Object_30.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_32"
                    geometry={nodes.Object_32.geometry}
                    material={materials.final_E}
                    skeleton={nodes.Object_32.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_34"
                    geometry={nodes.Object_34.geometry}
                    material={materials.final_A}
                    skeleton={nodes.Object_34.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
                <skinnedMesh
                    name="Object_36"
                    geometry={nodes.Object_36.geometry}
                    material={materials.final_rope}
                    skeleton={nodes.Object_36.skeleton}
                    rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.183}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/models/the_last_stronghold_animated-transformed.glb');
