// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tower.glb --transform 
Files: public/models/tower.glb [7.83MB] > /Users/stephenmatheis/GitHub/quest/tower-transformed.glb [387.66KB] (95%)
Author: luyssport (https://sketchfab.com/luyssport)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/hiih-13db62b151a44bed840b3502858cdcb7
Title: HiiH
*/

import { useGLTF } from '@react-three/drei';

export function Tower(props) {
    const { nodes, materials } = useGLTF('/models/tower-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.skybox.geometry}
                material={materials.skybox}
                position={[0, 17.468, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={4.216}
            />
            <mesh
                geometry={nodes.clouds.geometry}
                material={materials.clouds}
                position={[0, 17.468, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.47}
            />
            <mesh geometry={nodes.wm.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh
                geometry={nodes.grass.geometry}
                material={materials.grass}
                position={[0, 17.468, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.47}
            />
            <mesh geometry={nodes.outline.geometry} material={materials.outline} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
    );
}

useGLTF.preload('/models/tower-transformed.glb');
