// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BackPack.glb --transform 
Files: public/models/BackPack.glb [217.08KB] > /Users/stephenmatheis/GitHub/quest/BackPack-transformed.glb [19.38KB] (91%)
*/

import { useGLTF } from '@react-three/drei';

export function BackPack(props) {
    const { nodes, materials } = useGLTF('/models/BackPack-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Backpack_1.geometry} material={materials.DarkBrown} />
                <mesh geometry={nodes.Backpack_2.geometry} material={materials.Brown} />
                <mesh geometry={nodes.Backpack_3.geometry} material={materials.Gold} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/BackPack-transformed.glb');
