// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bag.glb --transform 
Files: public/models/Bag.glb [70.35KB] > /Users/stephenmatheis/GitHub/quest/Bag-transformed.glb [8.67KB] (88%)
*/

import { useGLTF } from '@react-three/drei';

export function Bag(props) {
    const { nodes, materials } = useGLTF('/models/Bag-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={71.166}>
                <mesh geometry={nodes.Bag_1.geometry} material={materials.Brown} />
                <mesh geometry={nodes.Bag_2.geometry} material={materials.DarkBrown} />
                <mesh geometry={nodes.Bag_3.geometry} material={materials.Gold} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/Bag-transformed.glb');
