// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Book.glb --transform 
Files: public/models/Book.glb [21.34KB] > /Users/stephenmatheis/GitHub/quest/Book-transformed.glb [4.56KB] (79%)
*/

import { useGLTF } from '@react-three/drei';

export function Book(props) {
    const { nodes, materials } = useGLTF('/models/Book-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Book2_Closed_1.geometry} material={materials.DarkRed} />
                <mesh geometry={nodes.Book2_Closed_2.geometry} material={materials.Golden} />
                <mesh geometry={nodes.Book2_Closed_3.geometry} material={materials.Beige} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/Book-transformed.glb');
