// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Book2.glb --transform 
Files: public/models/Book2.glb [61.62KB] > /Users/stephenmatheis/GitHub/quest/Book2-transformed.glb [8.5KB] (86%)
*/

import { useGLTF } from '@react-three/drei';

export function BoundBook(props) {
    const { nodes, materials } = useGLTF('/models/Book2-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Book3_Closed_1.geometry} material={materials.DarkBrown} />
                <mesh geometry={nodes.Book3_Closed_2.geometry} material={materials.Beige} />
                <mesh geometry={nodes.Book3_Closed_3.geometry} material={materials.Gold} />
                <mesh geometry={nodes.Book3_Closed_4.geometry} material={materials.Brown} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/Book2-transformed.glb');
