// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CuttingBoard.glb --transform 
Files: public/models/CuttingBoard.glb [9.11KB] > /Users/stephenmatheis/GitHub/quest/CuttingBoard-transformed.glb [2.54KB] (72%)
*/

import { useGLTF } from '@react-three/drei';

export function CuttingBoard(props) {
    const { nodes, materials } = useGLTF('/models/CuttingBoard-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.cuttingBoard_1.geometry} material={materials.brownLight} />
            <mesh geometry={nodes.cuttingBoard_1_1.geometry} material={materials.brownLight} />
            {/* <mesh geometry={nodes.cuttingBoard_1_1.geometry} material={materials.brown} /> */}
        </group>
    );
}

useGLTF.preload('/models/CuttingBoard-transformed.glb');
