// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Dagger.glb --transform 
Files: public/models/Dagger.glb [42.81KB] > /Users/stephenmatheis/GitHub/quest/Dagger-transformed.glb [4.78KB] (89%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Dagger(props) {
    const { nodes, materials } = useGLTF('/models/Dagger-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Dagger.geometry}
                material={materials.PaletteMaterial001}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
        </group>
    );
}

useGLTF.preload('/models/Dagger-transformed.glb');
