// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/DoubleSidedHammer.glb --transform 
Files: public/models/DoubleSidedHammer.glb [105.92KB] > /Users/stephenmatheis/GitHub/quest/DoubleSidedHammer-transformed.glb [12.3KB] (88%)
*/

import { useGLTF } from '@react-three/drei';

export function DoubleSidedHammer(props) {
    const { nodes, materials } = useGLTF('/models/DoubleSidedHammer-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Hammer_Double_1.geometry} material={materials.Steel} />
                <mesh geometry={nodes.Hammer_Double_2.geometry} material={materials.LightSteel} />
                <mesh geometry={nodes.Hammer_Double_3.geometry} material={materials.DarkWood} />
                <mesh geometry={nodes.Hammer_Double_4.geometry} material={materials.LightWood} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/DoubleSidedHammer-transformed.glb');
