// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Knife.glb --transform 
Files: public/models/Knife.glb [40.37KB] > /Users/stephenmatheis/GitHub/quest/Knife-transformed.glb [4.79KB] (88%)
*/

import { useGLTF } from '@react-three/drei';

export function Knife(props) {
    const { nodes, materials } = useGLTF('/models/Knife-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Dagger_2.geometry}
                material={materials.PaletteMaterial001}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
        </group>
    );
}

useGLTF.preload('/models/Knife-transformed.glb');
