// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/OpenBook.glb --transform 
Files: public/models/OpenBook.glb [25.17KB] > /Users/stephenmatheis/GitHub/quest/OpenBook-transformed.glb [3.85KB] (85%)
*/

import { useGLTF } from '@react-three/drei';

export function OpenBook(props) {
    const { nodes, materials } = useGLTF('/models/OpenBook-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Book1_Open_1.geometry} material={materials.Beige} />
                <mesh geometry={nodes.Book1_Open_2.geometry} material={materials.DarkRed} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/OpenBook-transformed.glb');
