// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Paper.glb --transform 
Files: public/models/Paper.glb [22.91KB] > /Users/stephenmatheis/GitHub/quest/Paper-transformed.glb [6.65KB] (71%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Paper(props) {
    const { nodes, materials } = useGLTF('/models/Paper-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.UI_Paper.geometry} material={materials.Atlas} scale={100} />
        </group>
    );
}

useGLTF.preload('/models/Paper-transformed.glb');
