// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Parchment.glb --transform 
Files: public/models/Parchment.glb [33KB] > /Users/stephenmatheis/GitHub/quest/Parchment-transformed.glb [3.89KB] (88%)
*/

import { useGLTF } from '@react-three/drei';

export function Parchment(props) {
    const { nodes, materials } = useGLTF('/models/Parchment-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Parchment.geometry}
                material={materials.Beige}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
        </group>
    );
}

useGLTF.preload('/models/Parchment-transformed.glb');
