// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Overhang_Roof_Plaster.gltf --transform -o /Users/stephenmatheis/GitHub/quest/Roof.jsx 
Files: Overhang_Roof_Plaster.gltf [3.74KB] > /Users/stephenmatheis/GitHub/quest/Overhang_Roof_Plaster-transformed.glb [741.29KB] (-19721%)
*/

import { useGLTF } from '@react-three/drei';

export function Roof(props) {
    const { nodes, materials } = useGLTF('/models/Overhang_Roof_Plaster-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Cube067.geometry} material={materials.MI_WoodTrim} />
            <mesh geometry={nodes.Cube067_1.geometry} material={materials.MI_Plaster} />
        </group>
    );
}

useGLTF.preload('/models/Overhang_Roof_Plaster-transformed.glb');
