// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ShieldRound.glb --transform 
Files: public/models/ShieldRound.glb [60.45KB] > /Users/stephenmatheis/GitHub/quest/ShieldRound-transformed.glb [8.5KB] (86%)
*/

import { useGLTF } from '@react-three/drei';

export function ShieldRound(props) {
    const { nodes, materials } = useGLTF('/models/ShieldRound-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Shield_Round_1.geometry} material={materials.LightWood} />
                <mesh geometry={nodes.Shield_Round_2.geometry} material={materials.Steel} />
                <mesh geometry={nodes.Shield_Round_3.geometry} material={materials.DarkWood} />
                <mesh geometry={nodes.Shield_Round_4.geometry} material={materials.LightSteel} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/ShieldRound-transformed.glb');
