// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Wall.glb --transform 
Files: public/models/Wall.glb [70.76KB] > /Users/stephenmatheis/GitHub/quest/Wall-transformed.glb [8.79KB] (88%)
*/

import { useGLTF } from '@react-three/drei';

export function StoneWall(props) {
    const { nodes, materials } = useGLTF('/models/StoneWall-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Wall_1.geometry} material={materials.Highlights} />
                <mesh geometry={nodes.Wall_2.geometry} material={materials.Main} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/StoneWall-transformed.glb');
