// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SwordWallMount.glb --transform 
Files: public/models/SwordWallMount.glb [136KB] > /Users/stephenmatheis/GitHub/quest/SwordWallMount-transformed.glb [11.11KB] (92%)
*/

import { useGLTF } from '@react-three/drei';

export function Sword_WallMount(props) {
    const { nodes, materials } = useGLTF('/models/SwordWallMount-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Sword_WallMount.geometry}
                material={materials.PaletteMaterial001}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
        </group>
    );
}

useGLTF.preload('/models/SwordWallMount-transformed.glb');
