// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Torch.glb --transform 
Files: public/models/Torch.glb [23.49KB] > /Users/stephenmatheis/GitHub/quest/Torch-transformed.glb [4.07KB] (83%)
*/

import { useGLTF } from '@react-three/drei';

export function Torch(props) {
    const { nodes, materials } = useGLTF('/models/Torch-transformed.glb');

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Torch_1.geometry} material={materials.DarkMetal} />
                <mesh geometry={nodes.Torch_2.geometry} material={materials.Fire} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/Torch-transformed.glb');
