// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WoodFloor.glb --transform 
Files: public/models/WoodFloor.glb [21.06KB] > /Users/stephenmatheis/GitHub/quest/WoodFloor-transformed.glb [6.25KB] (70%)
*/

import { useGLTF } from '@react-three/drei';

export function WoodFloor(props) {
    const { nodes, materials } = useGLTF('/models/WoodFloor-transformed.glb');
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Floor_Wood.geometry} material={materials.Atlas} scale={100} />
        </group>
    );
}

useGLTF.preload('/models/WoodFloor-transformed.glb');
