// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WoodenWall.glb --transform 
Files: public/models/WoodenWall.glb [18.62KB] > /Users/stephenmatheis/GitHub/quest/WoodenWall-transformed.glb [4.18KB] (78%)
*/

import { useGLTF } from '@react-three/drei';

export function WoodenWall(props) {
    const { nodes, materials } = useGLTF('/models/WoodenWall-transformed.glb');

    console.log(materials);

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Wall_FirstAge_1.geometry} material={materials.Wood} />
                <mesh geometry={nodes.Wall_FirstAge_2.geometry} material={materials.Wood_Light} />
            </group>
        </group>
    );
}

useGLTF.preload('/models/WoodenWall-transformed.glb');
